"""Focused tests for the initial PostgreSQL ORM schema."""

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKeyConstraint,
    UniqueConstraint,
    inspect,
)
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateTable

from app.db.base import Base
from app.models import FileMetadata, User


def _constraint_names(table: object, constraint_type: type[object]) -> set[str]:
    """Return named constraints of one kind from a SQLAlchemy table."""
    return {
        constraint.name
        for constraint in table.constraints  # type: ignore[attr-defined]
        if isinstance(constraint, constraint_type) and constraint.name is not None
    }


def test_initial_models_share_the_existing_declarative_metadata() -> None:
    """Alembic can discover both models through the Phase 1 declarative base."""
    assert User.metadata is Base.metadata
    assert FileMetadata.metadata is Base.metadata
    assert set(Base.metadata.tables) == {"users", "file_metadata"}


def test_user_table_has_only_the_initial_data_layer_fields() -> None:
    """The user model contains identity data without authentication behavior."""
    table = User.__table__

    assert set(table.columns.keys()) == {
        "id",
        "username",
        "password_hash",
        "role",
        "created_at",
    }
    assert isinstance(table.c.id.type, BigInteger)
    assert table.c.id.primary_key is True
    assert table.c.id.identity is not None
    assert table.c.username.nullable is False
    assert table.c.password_hash.nullable is False
    assert table.c.role.nullable is False
    assert table.c.created_at.nullable is False
    assert isinstance(table.c.created_at.type, DateTime)
    assert table.c.created_at.type.timezone is True
    assert "uq_users_username" in _constraint_names(table, UniqueConstraint)
    assert "ck_users_role_allowed" in _constraint_names(table, CheckConstraint)


def test_file_metadata_has_constraints_but_no_binary_content_column() -> None:
    """PostgreSQL stores object metadata only; file bytes remain external."""
    table = FileMetadata.__table__

    assert set(table.columns.keys()) == {
        "id",
        "owner_id",
        "original_filename",
        "s3_object_key",
        "content_type",
        "size_bytes",
        "created_at",
    }
    assert isinstance(table.c.id.type, BigInteger)
    assert table.c.id.primary_key is True
    assert table.c.id.identity is not None
    assert table.c.owner_id.nullable is False
    assert table.c.original_filename.nullable is False
    assert table.c.s3_object_key.nullable is False
    assert table.c.content_type.nullable is True
    assert table.c.size_bytes.nullable is False
    assert isinstance(table.c.size_bytes.type, BigInteger)
    assert isinstance(table.c.created_at.type, DateTime)
    assert table.c.created_at.type.timezone is True
    assert "uq_file_metadata_s3_object_key" in _constraint_names(
        table,
        UniqueConstraint,
    )
    assert "ck_file_metadata_size_bytes_nonnegative" in _constraint_names(
        table,
        CheckConstraint,
    )
    assert {index.name for index in table.indexes} == {
        "ix_file_metadata_owner_id"
    }


def test_file_owner_foreign_key_and_relationship_are_bidirectional() -> None:
    """Each file belongs to one user and deletion is database-restricted."""
    table = FileMetadata.__table__
    foreign_keys = [
        constraint
        for constraint in table.constraints
        if isinstance(constraint, ForeignKeyConstraint)
    ]

    assert len(foreign_keys) == 1
    foreign_key = foreign_keys[0]
    assert foreign_key.name == "fk_file_metadata_owner_id_users"
    assert foreign_key.ondelete == "RESTRICT"
    assert [element.target_fullname for element in foreign_key.elements] == [
        "users.id"
    ]

    user_files = inspect(User).relationships["files"]
    file_owner = inspect(FileMetadata).relationships["owner"]
    assert user_files.mapper.class_ is FileMetadata
    assert user_files.back_populates == "owner"
    assert user_files.passive_deletes == "all"
    assert file_owner.mapper.class_ is User
    assert file_owner.back_populates == "files"


def test_models_compile_to_postgresql_ddl() -> None:
    """The schema compiles with PostgreSQL identity and timestamp semantics."""
    dialect = postgresql.dialect()
    users_ddl = str(CreateTable(User.__table__).compile(dialect=dialect))
    files_ddl = str(CreateTable(FileMetadata.__table__).compile(dialect=dialect))

    assert "CREATE TABLE users" in users_ddl
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY" in users_ddl
    assert "TIMESTAMP WITH TIME ZONE" in users_ddl
    assert "CREATE TABLE file_metadata" in files_ddl
    assert "FOREIGN KEY(owner_id) REFERENCES users (id) ON DELETE RESTRICT" in files_ddl
    assert "CHECK (size_bytes >= 0)" in files_ddl
    assert "BYTEA" not in files_ddl
